export const actionTypes = {
  FILTER: "FILTER",
  SEARCH_FILTER: "SEARCH_FILTER",
  COMPILE_DATA: "COMPILE_DATA",
  ERASE_FORM_DATA: "ERASE_FORM_DATA",
  SET_TYPE_HOUSE: "SET_TYPE_HOUSE",
  SET_BEDROOMS: "SET_BEDROOMS",
  SET_BATHROOMS: "SET_BATHROOMS",
  SET_EQUIPMENT: "SET_EQUIPMENT",
  SET_CONDITION: "SET_CONDITION",
  SET_PRICE_RANGE: "SET_PRICE_RANGE",
  SET_PUBL_DATE: "SET_PUBL_DATE",
  SET_MORE_FILTERS: "SET_MORE_FILTERS",
};
