export const actionTypes = {
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  IS_SIGNING_IN: "IS_SIGNING_IN",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  SIGN_OUT: "SIGN_OUT",
};
